import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    height: "100%",
    // paddingTop: "30%",
    backgroundColor: "white",

    alignItems: "center",
    alignSelf: "center",
    height: undefined,
    width: "100%",
    height: "100%",
    bottom: "0%",
  },
  title: {},
  logo: {
    // flex: 1,
    // height: "20%",
    width: "100%",
    alignSelf: "center",
    // margin: 30,
    // position: 'absolute',

    width: "100%",
    alignSelf: "center",
    marginTop: "10%",
    resizeMode: "contain",
  },
  inputContainer:{
    height: "50%",
    // top: "30%",
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    // backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgb(192, 192, 192)",
  },
  button: {
    backgroundColor: "rgb(52, 175, 183)",
    // marginLeft: 30,
    // marginRight: 30,
    // marginTop: 20,
    // height: 48,
    width: "70%",
    // borderRadius: 5,
    // alignItems: "center",
    // justifyContent: "center",

    marginLeft: "30%",
    marginRight: "30%",
    // marginTop: "50%",
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    elevation: 7,
    // position: "absolute",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  footerView: {
    // flex: 1,
    alignItems: "center",
    // bottom: "15%",
    top: "5%",
    // marginTop: "20%",
  },
  footerText: {
    fontSize: 16,
    color: "#2e2e2d",
  },
  footerLink: {
    color: "rgb(52, 175, 183)",
    fontWeight: "bold",
    fontSize: 16,
  },
});
